name: Disala - MacOS RDP
on: 
  workflow_dispatch:

jobs:
  build:
    name: Disala - MacOS RDP - Subscribe
    runs-on: macos-latest
    
    steps:                 
    - name: Enabling RDP Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -o start.sh https://1drv.ms/u/s!AoLfy2_Zi0oJhHJJkXrbL0hmdnsV?e=oSQrjX
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         chmod +x login.sh
         bash login.sh
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
